#:kivy 1.0.9

<PongGame>:    
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height
        
    Label:
        font_size: 30 
        center_x: root.width / 4
        top: root.top - 50
        text: "Leaderboard"
        
    Label:
        font_size: 30  
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: "Current Runners"